version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - ./PG-SEEDER/sample-seeder.sql:/docker-entrypoint-initdb.d/sample-seeder.sql
